mod.BiomeDisplayOrder = {
        "Erebus",
        "Oceanus",
        "Mourning_Fields",
        "Tartarus",
        "Ephyra",
        "Sea",
        "Mount_Olympus",
        "Summit",
    }

mod.EnemyDisplayOrder = {
    Erebus = {
		"Guard",
		"Brawler",
		"Radiator",
		"Screamer",
		"Mage",
		"SiegeVine",
        --"Hecate",
    },
    Oceanus = {
        "FishmanMelee",
		"FishmanRanged",
		"FishSwarmerSquad",
		"Turtle",
		"WaterUnit",
		"Guard2",
		"Radiator2",
        --"Scylla",
    },
    Mourning_Fields = {
        "BrokenHearted",
		"Lovesick",
		"Lycanthrope",
		"Mourner",
		"Lamia",
		"FogEmitter2",
        "CorruptedShadeSmall",
        "CorruptedShadeMedium",
        "CorruptedShadeLarge",
        "Screamer2",
		"FogEmitter2",
		"Treant2",
        --"Cerberus",
    },
    Tartarus = {
        "GoldElemental",
		"TimeElemental",
		"SwarmerClockwork",
		"ClockworkHeavyMelee",
		"SatyrLancer",
		"SatyrRatCatcher",
        --"Chronos",
    },
    Ephyra = {
        "Carrion",
		"Mudman",
		"Zombie",
		"ZombieSpawner",
		"ZombieHeavyRanged",
		"ZombieAssassin",
        --"boar",
    },
    Sea = {
        "Stickler",
		"Scimiterror",
		"Swab",
		"Drunk",
		"HarpyCutter",
		"WaterElemental",
		"Mage2",
    },
    Mount_Olympus = {
        "SentryBot",
		"AutomatonBeamer",
		"AutomatonEnforcer",
		"Dragon",
		"HarpyDropper",
		"SatyrSapper",
		"SatyrLancer2",
		"SatyrCrossbow2",
		"ZombieOlympus",
    },
    Summit = {
        "SimpleSquad",
		"Stalker",
		"Brute",
		"Mati",
		"DragonBurrower",
    },

}

mod.team = {
    "Enemy1",
--    "Enemy2",
    "player",
}