mod.BiomeDisplayOrder = {
        "Erebus",
        "Oceanus",
        "Mourning_Fields",
        "Tartarus",
        "Ephyra",
        "Sea",
        "Mount_Olympus",
        "Summit",
    }

mod.TypeDisplayOrder = {
    "regular",
    "elite",
    "boss",
}

mod.EnemyDisplayOrder = {
    Erebus = {
        regular = {
            "Guard",
            "Brawler",
            "Radiator",
            "Screamer",
            "Mage",
            "SiegeVine",
            "Wisp",
            "LightRanged",
        },
        elite = {
            "Guard_Elite",
            "Brawler_Elite",
            "Radiator_Elite",
            "Screamer_Elite",
            "Mage_Elite",
            "SiegeVine_Elite",
        },
        boss = {
            "Treant",
            "TreantTail",
            "FogEmitter",
            "ZombieAssassin_Miniboss",
            "Hecate",
        },
    },
    Oceanus = {
        regular = {
            "FishmanMelee",
            "FishmanRanged",
            "FishSwarmer",
            "Turtle",
            "WaterUnit",
            "Guard2",
            "Radiator2",
            "Jellyfish",
            "ThiefMineLayer",
            "BloodMine",
        },
        elite = {
            "FishmanMelee_Elite",
            "FishmanRanged_Elite",
            "FishSwarmer_Elite",
            "Turtle_Elite",
            "WaterUnit_Elite",
            "Guard2_Elite",
            "Radiator2_Elite",
            "ThiefMineLayer_Elite",
        },
        boss = {
            "CrawlerMiniboss",
            "WaterUnitMiniboss",
            "Octofish",
            "SirenKeytarist",
            "SirenDrummer",
            "Scylla",
        },
    },
    Mourning_Fields = {
        regular = {
            "BrokenHearted",
            "Lovesick",
            "LovesickHeart",
            "Lycanthrope",
            "LycanSwarmer",
            "Mourner",
            "Lamia",
            "FogEmitter2",
            "CorruptedShadeSmall",
            "CorruptedShadeMedium",
            "CorruptedShadeLarge",
            "Screamer2",
            "FogEmitter2",
            "Treant2",
            "TreantTail2",
        },
        elite = {
            "BrokenHearted_Elite",
            "Lovesick_Elite",
            "Lycanthrope_Elite",
            "Mourner_Elite",
            "Lamia_Elite",
            "DespairElemental_Elite",
            "CorruptedShadeSmall_Elite",
            "CorruptedShadeMedium_Elite",
            "CorruptedShadeLarge_Elite",
            "Screamer2_Elite",
        },
        boss = {
            "Lamia_Miniboss",
            "Vampire",
            "InfestedCerberus",
        },
    },
    Tartarus = {
        regular = {
            "GoldElemental",
            "TimeElemental",
            "SwarmerClockwork",
            "ClockworkHeavyMelee",
            "SatyrLancer",
            "SatyrRatCatcher",
            "Crawler",
            "SatyrCultist",
        },
        elite = {
            "GoldElemental_Elite",
            "TimeElemental_Elite",
            "SwarmerClockwork_Elite",
            "ClockworkHeavyMelee_Elite",
            "SatyrLancer_Elite",
            "SatyrRatCatcher_Elite",
        },
        boss = {
            "GoldElemental_MiniBoss",
            "SatyrRatCatcher_Miniboss",
            "Zagreus",
            "Chronos",
        },
    },
    Ephyra = {
        regular = {
            "Carrion",
            "Mudman",
            "MudmanEye",
            "Zombie",
            "ZombieSpawner",
            "ZombieHeavyRanged",
            "ZombieAssassin",
            "Sheep_Explosive",
            "Sheep_Zombie",
            "Sheep_Sick",
        },
        elite = {
            "Carrion_Elite",
            "Mudman_Elite",
            "Zombie_Elite",
            "ZombieSpawner_Elite",
            "ZombieHeavyRanged_Elite",
            "ZombieAssassin_Elite",
        },
        boss = {
            "Boar",
            "SatyrCrossbow",
            "Polyphemus",
        },
    },
    Sea = {
        regular = {
            "Stickler",
            "Scimiterror",
            "Swab",
            "Drunk",
            "HarpyCutter",
            "WaterElemental",
            "Mage2",
        },
        elite = {
            "Stickler_Elite",
            "Scimiterror_Elite",
            "Swab_Elite",
            "Drunk_Elite",
            "HarpyCutter_Elite",
            "WaterElemental_Elite",
            "Mage2_Elite",
        },
        boss = {
            "CharybdisTentacle",
            "Charybdis",
            "Captain",
            "Eris",
        },
    },
    Mount_Olympus = {
        regular = {
            "SentryBot",
            "AutomatonBeamer",
            "AutomatonEnforcer",
            "Dragon",
            "HarpyDropper",
            "SatyrSapper",
            "SatyrLancer2",
            "SatyrCrossbow2",
            "ZombieOlympus",
        },
        elite = {
            "SentryBot_Elite",
            "AutomatonBeamer_Elite",
            "AutomatonEnforcer_Elite",
            "Dragon_Elite",
            "HarpyDropper_Elite",
            "SatyrSapper_Elite",
            "SatyrLancer2_Elite",
            "SatyrCrossbow2_Elite",
            "ZombieOlympus_Elite",
        },
        boss = {
            "Talos",
            "Dragon_MiniBoss",
            "Prometheus",
            "Heracles",
        },
    },
    Summit = {
        regular = {
            "Simple",
            "Stalker",
            "Brute",
            "Mati",
            "DragonBurrower",
            "EarthElemental",
        },
        elite = {
            "SimpleSquad_Elite",
            "Stalker_Elite",
            "Brute_Elite",
            "Mati_Elite",
            "DragonBurrower_Elite",
        },
        boss = {
            "TyphonEgg",
            "Eyeball",
            "Brute_Miniboss",
            "Stalker_Miniboss",
            "TyphonEye",
            "TyphonTailMine",
            "TyphonTail",
            "TyphonHead",
        },
    },

}

mod.team = {
    "Enemy1",
--    "Enemy2",
    "player",
}

if rom.mods['NikkelM-Zagreus_Journey'] then

	mod.BiomeDisplayOrder = {
        "Erebus",
        "Oceanus",
        "Mourning_Fields",
        "Tartarus",
        "Ephyra",
        "Sea",
        "Mount_Olympus",
        "Summit",
		"Tartarus_H1",
		"Asphodel",
		"Elysium",
		"Styx",
    }

	OverwriteTableKeys(mod.EnemyDisplayOrder,{
		Tartarus_H1 = {
            regular = {
                "HadesSwarmer",
                "LightSpawner",
                "HadesThiefMineLayer",
                "PunchingBagUnit",
                "HeavyMelee",
                "DisembodiedHand",
                "HadesLightRanged",
                "HeavyRanged",
            },
            elite = {
                "SwarmerElite",
                "HadesThiefMineLayerElite",
                "PunchingBagUnitElite",
                "HeavyMeleeElite",
                "DisembodiedHandElite",
                "LightRangedElite",
                "HeavyRangedElite",
            },
            boss = {
                "WretchAssassinMiniboss",
                "HeavyRangedSplitterMiniboss",
                "Harpy",
                "Harpy2",
                "Harpy3",
            },
		},
		Asphodel = {
            regular = {
                "CrusherUnit",
                "HadesBloodlessNaked",
                "BloodlessNakedBerserker",
                "HadesBloodlessGrenadier",
                "HadesBloodlessSelfDestruct",
                "HadesBloodlessPitcher",
                "HadesBloodlessWaveFist",
                "HadesSpreadShotUnit",
                "FreezeShotUnit",
                "RangedBurrower",
            },
            elite = {
                "LightSpawnerElite",
                "HadesBloodlessNakedElite",
                "BloodlessNakedBerserkerElite",
                "HadesBloodlessGrenadierElite",
                "HadesBloodlessSelfDestructElite",
                "HadesBloodlessPitcherElite",
                "HadesBloodlessWaveFistElite",
                "HadesSpreadShotUnitElite",
                "FreezeShotUnitElite",
                "RangedBurrowerElite",
            },
            boss = {
                "SpreadShotUnitMiniboss",
                "HitAndRunUnit",
                "HydraHeadDartmaker",
                "HydraHeadLavamaker",
                "HydraHeadSlammer",
                "HydraHeadWavemaker",
                "HydraHeadSummoner",
                "HydraHeadImmortal",
                "HydraHeadImmortalLavamaker",
                "HydraHeadImmortalSlammer",
                "HydraHeadImmortalWavemaker",
                "HydraHeadImmortalSummoner",
            },
		},
		Elysium = {
            regular = {
                "ShadeNaked",
                "ShadeSpearUnit",
                "ShadeBowUnit",
                "ShadeShieldUnit",
                "ShadeSwordUnit",
                "ShieldRanged",
                "SplitShotUnit",
                "Chariot",
                "ChariotSuicide",
                "FlurrySpawner",
            },
            elite = {
                "ShadeSpearUnitElite",
                "ShadeBowUnitElite",
                "ShadeShieldUnitElite",
                "ShadeSwordUnitElite",
                "ShieldRangedElite",
                "SplitShotUnitElite",
                "ChariotElite",
                "ChariotSuicideElite",
            },
            boss ={
                "Minotaur",
                "Theseus",
            },
		},
		Styx = {
            regular = {
                "HadesCrawler",
                "RatThug",
                "SatyrRanged",
                "HeavyRangedForked",
                "ThiefImpulseMineLayer",
            },
            elite = {
                "RatThugElite",
                "SatyrRangedElite",
                "HeavyRangedForkedElite",
                "ThiefImpulseMineLayerElite",
            },
            boss ={
                "SatyrRangedMiniboss",
                "RatThugMiniboss",
                "ThiefImpulseMineLayerMiniboss",
                "HeavyRangedForkedMiniboss",
                "HadesCrawlerMiniBoss",
                "Hades",
                "Charon",
            },
		}
	})
end